export const siteConfig = {
  name: "Boenha",
  title: "Boenha - CV Boenha Makmur Utama",
  description:
    "Penyedia ayam kampung berkualitas tinggi dengan sistem peternakan modern, berkelanjutan, dan terpercaya di Indonesia. Kami menyediakan ayam hidup dan ayam potong premium dengan standar kualitas internasional.",
  url: "https://boenha.com",
  ogImage: "https://boenha.com/assets/logo/logo.png",
  locale: "id_ID",
  author: "CV Boenha Makmur Utama",
  phone: "+6282315403127",
  email: "boenhamakmurutama@gmail.com",
  address: "Jl. Raya Bojong Genteng, Sukabumi, Jawa Barat, Indonesia",
  keywords: [
    "boenha",
    "ayam kampung",
    "peternakan ayam",
    "ayam organik",
    "ayam berkualitas",
    "Sukabumi",
    "peternakan berkelanjutan",
    "ayam potong",
    "ayam hidup",
    "ayam kampung hidup",
    "peternakan ayam organik",
  ],
  socialMedia: {
    whatsapp: "https://wa.me/6282315403127",
    facebook: "https://www.facebook.com/profile.php?id=61584727112231",
    instagram: "https://www.instagram.com/boenhamakmurutama",
    tiktok: "https://www.tiktok.com/@boenha",
    shopee: "https://shopee.co.id/boenha",
  },
};

export const schemaOrganization = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  name: "CV Boenha Makmur Utama",
  description: siteConfig.description,
  url: siteConfig.url,
  logo: `${siteConfig.url}/assets/logo/logo.png`,
  image: `${siteConfig.url}/assets/logo/logo.png`,
  foundingDate: "2015",
  priceRange: "$$",
  areaServed: [
    "Sukabumi",
    "Bogor",
    "Jakarta",
    "Bandung",
    "Jawa Barat",
    "Indonesia",
  ],
  contactPoint: {
    "@type": "ContactPoint",
    telephone: siteConfig.phone,
    contactType: "Customer Service",
    areaServed: "ID",
    availableLanguage: ["id", "en"],
  },
  address: {
    "@type": "PostalAddress",
    streetAddress: siteConfig.address,
    addressLocality: "Sukabumi",
    addressRegion: "Jawa Barat",
    postalCode: "43300",
    addressCountry: "ID",
  },
  email: siteConfig.email,
  telephone: siteConfig.phone,
  sameAs: [
    siteConfig.socialMedia.facebook,
    siteConfig.socialMedia.instagram,
    siteConfig.socialMedia.tiktok,
    siteConfig.socialMedia.whatsapp,
  ],
};
